name: GitHub Pages

on:
  push:
    branches:
      - source  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist